version: "3.1"

services:
  qr:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fnirs-apps/qr
    volumes:
      - /home/runner/example_data/BIDS-NIRS-Tapping-master/:/bids_dataset
    command: ["--sci-threshold", "0.6"]
